var animation = [
  {
    key: "B00OSTKZWM",
    category: "3D Animation",
    name: "Learn 3D Animation - The Ultimate NEW BLENDER 2.8 Course A-Z",
    seller: "Alan Ayoubi",
    price: 134.99,
    priceFraction: "99",
    stock: 96,
    star: 4.6,
    starCount: 81223,
    time: 18,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1961224_8876.jpg",
    url: "https://www.udemy.com/course/ultimateblendercourse/",
    features: "A-Z Guide to Learning 3D Animation in the NEW Blender 2.8!",
    shipping: 3.99,
  },
  {
    key: "B01H2E0J5M",
    category: "3D Animation",
    name: "Ultimate Blender 3D Character Creation & Animation Course",
    seller: "Jaysen Batchelor",
    price: 134.99,
    priceFraction: "99",
    stock: 5,
    star: 4.5,
    starCount: 97357,
    time: 11,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/2915650_9cb8.jpg",
    url: "https://www.udemy.com/course/blender3dcharacteranimation/",
    features:
      "Learn 3D character creation & animation in Blender 2.8 with this A-Z course great for beginners and all levels of skill",
    shipping: 7.99,
  },
  {
    key: "B0713WPJKX",
    category: "Blender",
    name: "Learn Blender 3D - The Project course",
    seller: "Martin Perhiniak",
    price: 134.99,
    priceFraction: "99",
    stock: 87,
    star: 4.5,
    starCount: 25192,
    time: 13,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/665142_2b12_3.jpg",
    url:
      "https://www.udemy.com/course/learn-blender-3d-project-course-your-1st-project/",
    features:
      "Learn the basics of modelling, materials, rigging, rendering and animation using Blender3D",
    shipping: 3.99,
  },
  {
    key: "B01LPZD1N6",
    category: "3D Animation",
    name: "Blender 3D Crash Course for Absolute Beginners",
    seller: "Cristian Doru Barin",
    price: 134.99,
    priceFraction: "90",
    stock: 20,
    star: 4.6,
    starCount: 19980,
    time: 14,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1928080_61a3_5.jpg",
    url:
      "https://www.udemy.com/course/blender-3d-crash-course-for-absolute-beginners/",
    features:
      "Learn to Create Custom 3D Models, Images & Animations Using FREE Software!",
    shipping: 0,
  },
  {
    key: "B01N1SE4EP",
    category: "After Effects",
    name: "Create 3D Intro Using Adobe After Effects & Element 3D",
    seller: "Lindsay Marsh",
    price: 134.99,
    priceFraction: "99.99",
    stock: 50,
    star: 4.6,
    starCount: 15064,
    time: 19.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/267978_c4ac_2.jpg",
    url:
      "https://www.udemy.com/course/create-3d-intro-using-adobe-after-effects/",
    features:
      "Almost every professional course, video or youtube channel has some short logo animation of the video's creator",
    shipping: 7.99,
  },
  {
    key: "B017LDNLIG",
    category: "Maya",
    name: "Maya Particles Course: Dynamic Particles and Motion Graphic",
    seller: "Daniel Walter Scott",
    price: 134.99,
    priceFraction: "94",
    stock: 85,
    star: 4.7,
    starCount: 13517,
    time: 10,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/488776_e4ab_4.jpg",
    url: "https://www.udemy.com/course/mayaparticles/",
    features:
      "Easily implement effects with this 3d animation tutorial in nParticles, nCloth, paint effects, soft bodies and more.",
    shipping: 7.99,
  },
  {
    key: "B018IZ0SWI",
    category: "Photoshop",
    name: "The Ultimate 2D/3D Photoshop & Graphic Design Course ! 2020",
    seller: "Derrick Mitchell",
    price: 139.99,
    priceFraction: "99",
    stock: 10,
    star: 4.5,
    starCount: 13058,
    time: 15.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/778740_5339_10.jpg",
    url:
      "https://www.udemy.com/course/the-ultimate-photoshop-graphic-design-course-2019/",
    features:
      "Learn 2D & 3D Design skills with PhotoEditing, Posters, social media design, Face Retouching & Animation Techniques.",
    shipping: 3.99,
  },
  {
    key: "B01N4HS7B8",
    category: "Blender",
    name: "Blender Pixar Animation Character course masterclass",
    seller: "Video School Online Inc",
    price: 134.99,
    priceFraction: "99",
    stock: 34,
    star: 4.7,
    starCount: 11534,
    time: 8.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/3397420_0b67_2.jpg",
    url:
      "https://www.udemy.com/course/blender-pixar-animation-character-course-masterclass/",
    features:
      "Blender, blender character, 3D Modelling, 3D Animation, animation, blender 3d, blender animation, 3D, blender texture,",
    shipping: 7.99,
  },
  {
    key: "B01LX0JZUM",
    category: "3D Animation",
    name: "Learn Cinema 4D from Scratch Fast and Easy",
    seller: "Daniel Walter Scott",
    price: 134.99,
    priceFraction: "99",
    stock: 8,
    star: 4.7,
    starCount: 8784,
    time: 7,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1172312_05b7_2.jpg",
    url:
      "https://www.udemy.com/course/learn-3d-design-in-cinema-4d-from-scratch-fast-and-easy/",
    features:
      "In this course you will learn in a fast way, how to create your own 3D models, Texturing, Animation and much more!!",
    shipping: 3.99,
  },
  {
    key: "B072NYXDLY",
    category: "Fusion 360",
    name: "Fusion 360 Beginners Course",
    seller: "Martin Perhiniak",
    price: 139.99,
    priceFraction: "99",
    stock: 14,
    star: 4.6,
    starCount: 7796,
    time: 13.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/2668390_ddc5.jpg",
    url: "https://www.udemy.com/course/fusion-360-beginners-course/",
    features:
      "Learn 3D Modeling, Assembly, Drawing, Rendering, Animation and Motion study in Fusion 360 from scratch",
    shipping: 3.99,
  },
  {
    key: "B071RK857H",
    category: "SOLIDWORKS",
    name: "SolidWorks: The Complete Design and Rendering Course",
    seller: "Eduonix-Tech",
    price: 149.99,
    priceFraction: "99",
    stock: 1,
    star: 4.4,
    starCount: 2328,
    time: 3.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1252012_dd6c_5.jpg",
    url:
      "https://www.udemy.com/course/solidworks-the-complete-design-and-rendering-course/",
    features:
      "Designing tutorials that are perfect for beginners: create 3D models, 2D drawings, assembly, animation and render.",
    shipping: 7.99,
  },
  {
    key: "B06XWMQRS6",
    category: "AutoCAD",
    name: "Complete ZWCAD Course",
    seller: "Irfan Dayan",
    price: 74.99,
    priceFraction: "99",
    stock: 54,
    star: 4.4,
    starCount: 2921,
    time: 92,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/2618978_f88c.jpg",
    url:
      "https://www.udemy.com/course/zwcad-computer-aided-design-software-cad/",
    features:
      "ZWCAD Software With 2D creation & Modification, 3D Creation & Modification, Layout creation, Image & Animation Creation",
    shipping: 3.99,
  },
  {
    key: "B01N41AKT3",
    category: "Animation",
    name: "Space Render 1.0: Artificial Intelligence in 3D Animation",
    seller: "Learn Tech Plus",
    price: 134.99,
    priceFraction: "99",
    stock: 66,
    star: 4.1,
    starCount: 2782,
    time: 102,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/3087860_a5ce_2.jpg",
    url:
      "https://www.udemy.com/course/space-render-10-artificial-intelligence-in-3d-animation/",
    features:
      "Create wow-inspiring 3D Animation and VFX Video super-fast using Cloud-Based Artificial Intelligence (AI) Tools",
    shipping: 3.99,
  },
  {
    key: "B06XY8W1DC",
    category: "Blender",
    name: "Complete Blender Creator: Learn 3D Modelling for Beginners",
    seller: "Nick Walter",
    price: 134.99,
    priceFraction: "99",
    stock: 97,
    star: 4.5,
    starCount: 4762,
    time: 76,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/438522_500f_6.jpg",
    url: "https://www.udemy.com/course/blendertutorial/",
    features:
      "Use Blender to Create Beautiful 3D models for Video Games, 3D Printing & More. Beginners Level Course",
    shipping: 7.99,
  },
  {
    key: "B01N0VVQ13",
    category: "Blender",
    name: "Creating 3D environments in Blender",
    seller: "Creative Online School",
    price: 134.99,
    priceFraction: "99",
    stock: 80,
    star: 4.3,
    starCount: 1206,
    time: 41,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/683198_ef78_7.jpg",
    url: "https://www.udemy.com/course/blender-environments/",
    features:
      "This course helps you creating wonderful environment scenes, organizing your workflow, and find the right inspiration.",
    shipping: 7.99,
  },
  {
    key: "B01JOT42JW",
    category: "Blender",
    name: "Blender 3D Modeling & Animation : 20+ 3D Projects in Blender",
    seller: "Framework Television Inc, Mark Lassoff",
    price: 19.99,
    priceFraction: "99",
    stock: 54,
    star: 4.4,
    starCount: 547,
    time: 23,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1150682_bb0d_4.jpg",
    url:
      "https://www.udemy.com/course/blender-3d-modelling-for-unity-game-development/",
    features:
      "Learn Blender 3D Modeling Animation UV Mapping Texture Painting .Build Game Assets, Learn 3D Game development with Unity",
    shipping: 3.99,
  },
  {
    key: "B06Y5PY61J",
    category: "3D Animation",
    name: "Learn 3D Animation - The Ultimate Blender Guide",
    seller: "David Joseph Katz",
    price: 59.99,
    priceFraction: "99",
    stock: 34,
    star: 4.4,
    starCount: 4176,
    time: 92,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/922654_100d.jpg",
    url: "https://www.udemy.com/course/blendercourse/",
    features:
      "A-Z Guide to Learning 3D Animation and Modeling With Blender to Set You on Your Way to Creating Awesome 3D Artwork",
    shipping: 7.99,
  },
  {
    key: "B0182YJ4V6",
    category: "Unity",
    name: "3D Animation using Unity Timeline",
    seller: "YouAccel Training",
    price: 99.99,
    priceFraction: "50",
    stock: 97,
    star: 4.3,
    starCount: 634,
    time: 72,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/2121514_a2c2.jpg",
    url: "https://www.udemy.com/course/3d-animation-using-unity-timeline/",
    features:
      "Learn 3D animation like a professional using Unity Timeline with this comprehensive guide",
    shipping: 7.99,
  },
  {
    key: "B01GL7EB50",
    category: "Unity",
    name: "3D Pixel Characters Modeling & Animations for all. Unity 3D",
    seller: "Evan Kimbrell",
    price: 134.99,
    priceFraction: "99",
    stock: 68,
    star: 4.4,
    starCount: 1396,
    time: 74,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/676088_1c1a.jpg",
    url:
      "https://www.udemy.com/course/3d-pixel-characters-modeling-animations-for-all-unity-3d/",
    features:
      "Step by step video lessons to master 3D pixel art to make characters and PRO animations for Unity3D, cocos2d and likes",
    shipping: 7.99,
  },
  {
    key: "B06XKH29C8",
    category: "3D Animation",
    name: "Turn a 2d photo into a 3d animation with After Effects!",
    seller: "Robert Kanaat",
    price: 134.99,
    priceFraction: "00",
    stock: 95,
    star: 4.7,
    starCount: 1150,
    time: 80,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/734144_6a0b_9.jpg",
    url:
      "https://www.udemy.com/course/2d-to-3d-with-photoshop-and-after-effects/",
    features:
      "Learn the basics of Photoshop and After Effects and create your own 3D animations from scratch!",
    shipping: 3.99,
  },
];

export default animation;
