var graphicDesign = [
  {
    key: "B00OSTKZWM",
    id: 21,
    category: "Photoshop",
    name: "Adobe Photoshop Mega Course-From Beginner to Super Designer",
    seller: "Alan Ayoubi",
    price: 134.99,
    priceFraction: "99",
    stock: 96,
    star: 4.6,
    starCount: 81223,
    time: 18,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/3384040_67c1.jpg",
    url:
      "https://www.udemy.com/course/the-ultimate-drawing-course-beginner-to-advanced/",
    features: "Adobe Photoshop CC 2020 - Master Photoshop Like a Pro Designer",
    shipping: 3.99,
  },
  {
    key: "B01H2E0J5M",
    id: 22,
    category: "Drawing",
    name: "The Ultimate Drawing Course - Beginner to Advanced",
    seller: "Jaysen Batchelor",
    price: 134.99,
    priceFraction: "99",
    stock: 5,
    star: 4.5,
    starCount: 97357,
    time: 11,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/874012_c7f2_3.jpg",
    url:
      "https://www.udemy.com/course/the-ultimate-drawing-course-beginner-to-advanced/",
    features: "Learn the #1 most important building block of all art",
    shipping: 7.99,
  },
  {
    key: "B0713WPJKX",
    id: 23,
    category: "Adobe Illustrator",
    name: "Illustrator CC 2020 MasterClass",
    seller: "Martin Perhiniak",
    price: 134.99,
    priceFraction: "99",
    stock: 87,
    star: 4.5,
    starCount: 25192,
    time: 13,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1197206_7201_3.jpg",
    url: "https://www.udemy.com/course/illustrator-cc-masterclass/",
    features:
      "Master Adobe Illustrator CC with this in-depth training for all levels.",
    shipping: 3.99,
  },
  {
    key: "B01LPZD1N6",
    id: 24,
    category: "Photoshop",
    name: "Ultimate Photoshop Training: From Beginner to Pro",
    seller: "Cristian Doru Barin",
    price: 134.99,
    priceFraction: "90",
    stock: 20,
    star: 4.6,
    starCount: 19980,
    time: 14,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1046722_cbd7_2.jpg",
    url:
      "https://www.udemy.com/course/ultimate-photoshop-training-from-beginner-to-pro/",
    features:
      "Master Photoshop CC 2020 without any previous knowledge with this easy-to-follow course",
    shipping: 0,
  },
  {
    key: "B01N1SE4EP",
    id: 25,
    category: "Graphic Design",
    name: "Graphic Design Masterclass - Learn GREAT Design",
    seller: "Lindsay Marsh",
    price: 134.99,
    priceFraction: "99.99",
    stock: 50,
    star: 4.6,
    starCount: 15064,
    time: 19.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1643044_e281.jpg",
    url:
      "https://www.udemy.com/course/graphic-design-masterclass-everything-you-need-to-know/",
    features:
      "The Ultimate Graphic Design Course Which Covers Photoshop, Illustrator, InDesign,Design Theory, Branding and Logo Design",
    shipping: 7.99,
  },
  {
    key: "B017LDNLIG",
    id: 26,
    category: "Photoshop",
    name: "Adobe Photoshop CC – Essentials Training Course",
    seller: "Daniel Walter Scott",
    price: 134.99,
    priceFraction: "94",
    stock: 85,
    star: 4.7,
    starCount: 13517,
    time: 10,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1747782_399b_2.jpg",
    url:
      "https://www.udemy.com/course/adobe-photoshop-cc-essentials-training-course/",
    features:
      "This Adobe Photoshop Essentials course will teach you Photoshop Retouching as well as Photoshop for graphic design.",
    shipping: 7.99,
  },
  {
    key: "B018IZ0SWI",
    id: 27,
    category: "Graphic Design",
    name: "Graphic Design Bootcamp: Photoshop, Illustrator, InDesign",
    seller: "Derrick Mitchell",
    price: 139.99,
    priceFraction: "99",
    stock: 10,
    star: 4.5,
    starCount: 13058,
    time: 15.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/749542_4762_3.jpg",
    url: "https://www.udemy.com/course/graphic-design-for-beginners/",
    features:
      "Bestselling Beginner Course! Use Photoshop, Illustrator, & InDesign for logo design, web design, poster design, and more",
    shipping: 3.99,
  },
  {
    key: "B01N4HS7B8",
    id: 28,
    category: "Adobe Illustrator",
    name: "Adobe Illustrator CC - Essentials Training Course",
    seller: "Video School Online Inc",
    price: 134.99,
    priceFraction: "99",
    stock: 34,
    star: 4.7,
    starCount: 11534,
    time: 8.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1514258_3768_2.jpg",
    url: "https://www.udemy.com/course/adobe-illustrator-course/",
    features:
      "Learn Adobe Illustrator CC graphic design, logo design, and more with this in-depth, practical, easy-to-follow course!",
    shipping: 7.99,
  },
  {
    key: "B01LX0JZUM",
    id: 29,
    category: "InDesign",
    name: "Adobe InDesign CC - Essentials Training Course",
    seller: "Daniel Walter Scott",
    price: 134.99,
    priceFraction: "99",
    stock: 8,
    star: 4.7,
    starCount: 8784,
    time: 7,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1316728_26f9_5.jpg",
    url: "https://www.udemy.com/course/indesign-tutorial-basics-course/",
    features:
      "Build company newsletters, brochures, annual reports. Learn typography, color theory & graphic design skills in InDesign",
    shipping: 3.99,
  },
  {
    key: "B072NYXDLY",
    id: 30,
    category: "Photoshop",
    name: "Photoshop CC 2020 MasterClass",
    seller: "Martin Perhiniak",
    price: 139.99,
    priceFraction: "99",
    stock: 14,
    star: 4.6,
    starCount: 7796,
    time: 13.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/850426_5596_3.jpg",
    url: "https://www.udemy.com/course/photoshop-cc-masterclass/",
    features:
      "Master the World's Best Imaging and Design Application and Become an Adobe Certified Associate.",
    shipping: 3.99,
  },
  {
    key: "B071RK857H",
    id: 31,
    category: "Mobile App Design",
    name: "Sketch from A to Z (2020): Become an app designer",
    seller: "Eduonix-Tech",
    price: 149.99,
    priceFraction: "99",
    stock: 1,
    star: 4.4,
    starCount: 2328,
    time: 3.5,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/371074_6c73_2.jpg",
    url: "https://www.udemy.com/course/learnsketch3/",
    features:
      "Finally a comprehensive guide to using Sketch for designing mobile applications. Learn to design an app from A to Z.",
    shipping: 7.99,
  },
  {
    key: "B06XWMQRS6",
    id: 32,
    category: "Photoshop",
    name: "Photoshop In-Depth: Master all of Photoshop's Tools Easily",
    seller: "Irfan Dayan",
    price: 74.99,
    priceFraction: "99",
    stock: 54,
    star: 4.4,
    starCount: 2921,
    time: 92,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/348116_e9d8_5.jpg",
    url: "https://www.udemy.com/course/photoshop-tools/",
    features:
      "Learn the many tools in Adobe Photoshop with in-depth lectures that explain the tool uses, options + modes in Photoshop.",
    shipping: 3.99,
  },
  {
    key: "B01N41AKT3",
    id: 33,
    category: "Digital Painting",
    name: "The Ultimate Digital Painting Course - Beginner to Advanced",
    seller: "Learn Tech Plus",
    price: 134.99,
    priceFraction: "99",
    stock: 66,
    star: 4.1,
    starCount: 2782,
    time: 102,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/869812_1fc8_3.jpg",
    url:
      "https://www.udemy.com/course/the-ultimate-digital-painting-course-beginner-to-advanced/",
    features:
      "Everything from drawing fundamentals to professional painting techniques",
    shipping: 3.99,
  },
  {
    key: "B06XY8W1DC",
    id: 34,
    category: "Design Theory",
    name: "The Complete Graphic Design Theory for Beginners Course",
    seller: "Nick Walter",
    price: 134.99,
    priceFraction: "99",
    stock: 97,
    star: 4.5,
    starCount: 4762,
    time: 76,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1864390_96a5_2.jpg",
    url:
      "https://www.udemy.com/course/graphic-design-theory-for-beginners-course/",
    features:
      "Learn Graphic Design Theory and the Basic Principles of Color Theory, Typography, Branding, Logo Design, Layout & More!",
    shipping: 7.99,
  },
  {
    key: "B01N0VVQ13",
    id: 35,
    category: "Figure Drawing",
    name: "Anatomy for Figure Drawing: Mastering the Human Figure",
    seller: "Creative Online School",
    price: 134.99,
    priceFraction: "99",
    stock: 80,
    star: 4.3,
    starCount: 1206,
    time: 41,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/62721_eed7_11.jpg",
    url: "https://www.udemy.com/course/anatomy-for-figure-drawing-and-comics/",
    features:
      "This is what you need to learn in order to draw figures like a pro and land that dream job.",
    shipping: 7.99,
  },
  {
    key: "B01JOT42JW",
    id: 36,
    category: "Photoshop",
    name: "Adobe Photoshop CC – Advanced Training Course",
    seller: "Framework Television Inc, Mark Lassoff",
    price: 19.99,
    priceFraction: "99",
    stock: 54,
    star: 4.4,
    starCount: 547,
    time: 23,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1835828_92e5.jpg",
    url:
      "https://www.udemy.com/course/adobe-photoshop-cc-advanced-training-course-tutorial/",
    features:
      "You'll learn advanced Photoshop techniques like Photoshop retouching & Graphic Design tutorials.",
    shipping: 3.99,
  },
  {
    key: "B06Y5PY61J",
    id: 37,
    category: "Adobe Illustrator",
    name: "Adobe Illustrator CC – Advanced Training Course",
    seller: "David Joseph Katz",
    price: 59.99,
    priceFraction: "99",
    stock: 34,
    star: 4.4,
    starCount: 4176,
    time: 92,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1623798_db31_3.jpg",
    url: "https://www.udemy.com/course/adobe-illustrator-cc-advanced-training/",
    features:
      "In this Adobe Illustrator Advanced course we'll learn Advanced techniques for graphic design, logo design & illustration",
    shipping: 7.99,
  },
  {
    key: "B0182YJ4V6",
    id: 38,
    category: "Digital Art",
    name: "Complete Beginners Guide to Digital Art",
    seller: "YouAccel Training",
    price: 99.99,
    priceFraction: "50",
    stock: 97,
    star: 4.3,
    starCount: 634,
    time: 72,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/327666_82b2_2.jpg",
    url: "https://www.udemy.com/course/digital-art-101-from-beginner-to-pro/",
    features:
      "Master the foundations of digital drawing and illustration and create art like a pro",
    shipping: 7.99,
  },
  {
    key: "B01GL7EB50",
    id: 39,
    category: "Sketching",
    name: "How to Draw and Sketch for Absolute Beginners",
    seller: "Evan Kimbrell",
    price: 134.99,
    priceFraction: "99",
    stock: 68,
    star: 4.4,
    starCount: 1396,
    time: 74,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1047436_97b3.jpg",
    url: "https://www.udemy.com/course/drawing-and-sketching-for-beginners/",
    features: "Learn the Basics of Sketching and Drawing",
    shipping: 7.99,
  },
  {
    key: "B06XKH29C8",
    id: 40,
    category: "Character Design",
    name: "The Ultimate Character Design School - Beginner to Advanced",
    seller: "Robert Kanaat",
    price: 134.99,
    priceFraction: "00",
    stock: 95,
    star: 4.7,
    starCount: 1150,
    time: 80,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/2509634_a995_8.jpg",
    url:
      "https://www.udemy.com/course/the-ultimate-character-design-school-beginner-to-advanced/",
    features: "Learn the concept industries number on job skill",
    shipping: 3.99,
  },
];

export default graphicDesign;
