var webDev = [
  {
    key: "B00OSTKZWM",
    id: 41,
    category: "Web Development",
    name: "The Complete 2020 Web Development Bootcamp",
    seller: "Dr.Angela Yu",
    price: 134,
    priceFraction: "99",
    stock: 96,
    star: 4.7,
    starCount: 81223,
    time: 54,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1565838_e54e_11.jpg",
    url: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    features:
      "Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB and more!",
    shipping: 3.99,
  },
  {
    key: "B01H2E0J5M",
    id: 42,
    category: "Web Development",
    name: "The Web Developer Bootcamp",
    seller: "Colt Steele",
    price: 134.99,
    priceFraction: "99",
    stock: 5,
    star: 4.6,
    starCount: 180402,
    time: 55,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
    url: "https://www.udemy.com/course/the-web-developer-bootcamp/",
    features:
      "The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
    shipping: 7.99,
  },
  {
    key: "B0713WPJKX",
    id: 43,
    category: "Web Development",
    name: "The Complete Web Developer Course 2.0",
    seller: "Rob Percival, Codestars by Rob Percival",
    price: 134.99,
    priceFraction: "99",
    stock: 87,
    star: 4.5,
    starCount: 62475,
    time: 45,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/764164_de03_2.jpg",
    url: "https://www.udemy.com/course/the-complete-web-developer-course-2/",
    features:
      "Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more!",
    shipping: 3.99,
  },
  {
    key: "B01LPZD1N6",
    id: 44,
    category: "Web Development",
    name: "The Complete Front-End Web Development Course!",
    seller: "Joseph Delgadilo, Nick Germaine",
    price: 134.99,
    priceFraction: "90",
    stock: 20,
    star: 4.3,
    starCount: 8773,
    time: 75,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1166306_84a1_3.jpg",
    url: "https://www.udemy.com/course/front-end-web-development/",
    features:
      "Get started as a front-end web developer using HTML, CSS, JavaScript, jQuery, and Bootstrap!",
    shipping: 0,
  },
  {
    key: "B01N1SE4EP",
    id: 45,
    category: "Full Stack Web Development",
    name: "Beginner Full Stack Web Development: HTML, CSS, React & Node",
    seller: "Mark Wahlbeck",
    price: 134.99,
    priceFraction: "99.99",
    stock: 50,
    star: 4.5,
    starCount: 8532,
    time: 85,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1042110_ffc3_4.jpg",
    url: "https://www.udemy.com/course/ultimate-web/",
    features:
      "Learn web development with HTML, CSS, Bootstrap 4, ES6 React and Node",
    shipping: 7.99,
  },
  {
    key: "B017LDNLIG",
    id: 46,
    category: "Web Development",
    name: "The Complete 2020 Web Development Course - Build 15 Projects",
    seller: "Development Island (UK)",
    price: 134.99,
    priceFraction: "94",
    stock: 85,
    star: 4.5,
    starCount: 5053,
    time: 35,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/548278_b005_9.jpg",
    url: "https://www.udemy.com/course/complete-web-development-course/",
    features:
      "The only course you need to become a full-stack web developer. Covers HTML5, CSS3, JS, ES6, Node, APIs, Mobile & more!",
    shipping: 7.99,
  },
  {
    key: "B018IZ0SWI",
    id: 47,
    category: "Web Development",
    name: "Web Development Masterclass - Complete Certificate Course",
    seller: "YouAccel Training",
    price: 139.99,
    priceFraction: "99",
    stock: 10,
    star: 4.3,
    starCount: 3784,
    time: 76,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/965528_737d_5.jpg",
    url:
      "https://www.udemy.com/course/web-development-masterclass-complete-certificate-course/",
    features:
      "Learn to setup virtual cloud servers and develop database-driven websites using the latest web technologies.",
    shipping: 3.99,
  },
  {
    key: "B01N4HS7B8",
    id: 48,
    category: "Responsive Design",
    name: "Learn Responsive Web Development from Scratch",
    seller: "Eduonix-Tech",
    price: 19.99,
    priceFraction: "99",
    stock: 34,
    star: 4.4,
    starCount: 4492,
    time: 63,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/128946_c9cb_6.jpg",
    url:
      "https://www.udemy.com/course/learn-responsive-web-development-from-scratch/",
    features:
      "A Comprehensive Course on Responsive Web Design and Twitter Bootstrap 3",
    shipping: 7.99,
  },
  {
    key: "B01LX0JZUM",
    id: 49,
    category: "Web Development",
    name: "Web Development - Complete Fast Track Course",
    seller: "Ruben Giuliani",
    price: 134.99,
    priceFraction: "99",
    stock: 8,
    star: 4.2,
    starCount: 2873,
    time: 78,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1788518_5aa0_9.jpg",
    url: "https://www.udemy.com/course/web-development-fast-track/",
    features:
      "Become a full-stack web developer in a month. Master HTML, CSS, Javascript, JQuery, PHP, MySQL and more!",
    shipping: 3.99,
  },
  {
    key: "B072NYXDLY",
    id: 50,
    category: "Web Development",
    name: "Practical Web Development: 22 Courses in 1",
    seller: "Creative Online School",
    price: 134.99,
    priceFraction: "99",
    stock: 14,
    star: 4.2,
    starCount: 2285,
    time: 76,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1415652_ad99_4.jpg",
    url: "https://www.udemy.com/course/the-complete-web-development-course/",
    features:
      "Learn PHP, Apache, MySQL, MongoDB, Python, JavaScript, XML, JSON, HTML, CSS, Wordpress and more. With practical examples",
    shipping: 3.99,
  },
  {
    key: "B071RK857H",
    id: 51,
    category: "Web Development",
    name: "The Full Stack Web Development",
    seller: "Eduonix-Tech",
    price: 59.99,
    priceFraction: "99",
    stock: 1,
    star: 4.4,
    starCount: 2328,
    time: 52,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1002676_3c6e_2.jpg",
    url: "https://www.udemy.com/course/the-full-stack-web-development/",
    features: "Learn Full Stack Web Development Building Over 40+ Projects",
    shipping: 7.99,
  },
  {
    key: "B06XWMQRS6",
    id: 52,
    category: "JavaScript",
    name: "Learn JavaScript for Web Development",
    seller: "Irfan Dayan",
    price: 74.99,
    priceFraction: "99",
    stock: 54,
    star: 4.4,
    starCount: 2921,
    time: 92,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/917724_114b_12.jpg",
    url:
      "https://www.udemy.com/course/javascript-learn-javascript-essentials-and-build-project/",
    features:
      "Advance your Web Development Skills By Learning Javascript from JavaScript Expert!",
    shipping: 3.99,
  },
  {
    key: "B01N41AKT3",
    id: 53,
    category: "Front End Web Development",
    name: "Front End Web Development For Beginners (A Practical Guide)",
    seller: "Learn Tech Plus",
    price: 134.99,
    priceFraction: "99",
    stock: 66,
    star: 4.1,
    starCount: 2782,
    time: 102,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1691862_eba9_3.jpg",
    url: "https://www.udemy.com/course/learn-front-end-development/",
    features:
      "Learn Front-End Web Development: Quickly Master HTML5, CSS3, JS, Bootstrap: By Building A Project From Scratch",
    shipping: 3.99,
  },
  {
    key: "B06XY8W1DC",
    id: 54,
    category: "Django",
    name: "Django 2.2 & Python | The Ultimate Web Development Bootcamp",
    seller: "Nick Walter",
    price: 134.99,
    priceFraction: "99",
    stock: 97,
    star: 4.5,
    starCount: 4762,
    time: 76,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1562632_a245_2.jpg",
    url:
      "https://www.udemy.com/course/the-ultimate-beginners-guide-to-django-django-2-python-web-dev-website/",
    features:
      "Build three complete websites, learn back and front-end web development, and publish your site online with DigitalOcean",
    shipping: 7.99,
  },
  {
    key: "B01N0VVQ13",
    id: 55,
    category: "Front End Web Development",
    name: "Complete Responsive Web Development: 4 courses in 1",
    seller: "Creative Online School",
    price: 134.99,
    priceFraction: "99",
    stock: 80,
    star: 4.3,
    starCount: 1206,
    time: 41,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1426718_abb7_2.jpg",
    url: "https://www.udemy.com/course/responsive-web-development/",
    features:
      "Master yourself in HTML5, CSS3, Bootstrap, jQuery and responsive web development",
    shipping: 7.99,
  },
  {
    key: "B01JOT42JW",
    id: 56,
    category: "Web Development",
    name: "Introduction to Web Development",
    seller: "Framework Television Inc, Mark Lassoff",
    price: 19.99,
    priceFraction: "99",
    stock: 54,
    star: 4.4,
    starCount: 547,
    time: 23,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/99986_6cb4_10.jpg",
    url: "https://www.udemy.com/course/introduction-to-web-development/",
    features:
      "Are you Interested in Learning Web Development? Enroll in this Free course for a Dynamic Introduction to the Profession!",
    shipping: 3.99,
  },
  {
    key: "B06Y5PY61J",
    id: 57,
    category: "React",
    name: "React JS Web Development - The Essentials Bootcamp",
    seller: "David Joseph Katz",
    price: 59.99,
    priceFraction: "99",
    stock: 34,
    star: 4.4,
    starCount: 4176,
    time: 92,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/1078522_f455_3.jpg",
    url: "https://www.udemy.com/course/react-js-and-redux-mastering-web-apps/",
    features:
      "Bootcamp on the React.js essentials. Gain a strong foundation of the core concepts, and build exciting and useful apps!",
    shipping: 7.99,
  },
  {
    key: "B0182YJ4V6",
    id: 58,
    category: "Web Development",
    name: "Internet and Web Development Fundamentals",
    seller: "YouAccel Training",
    price: 99.99,
    priceFraction: "50",
    stock: 97,
    star: 4.3,
    starCount: 634,
    time: 72,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/2334226_3436.jpg",
    url:
      "https://www.udemy.com/course/internet-and-web-development-fundamentals/",
    features:
      "Learn how the Internet Works and Setup a Testing & Production Web Server",
    shipping: 7.99,
  },
  {
    key: "B01GL7EB50",
    id: 59,
    category: "Home Business",
    name: "Running a Web Development Business: The Complete Guide",
    seller: "Evan Kimbrell",
    price: 134.99,
    priceFraction: "99",
    stock: 68,
    star: 4.4,
    starCount: 1396,
    time: 74,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/369662_7246_2.jpg",
    url:
      "https://www.udemy.com/course/the-complete-guide-to-running-a-web-development-business/",
    features:
      "Learn how to start and grow a successful web development business. Get up & running and making sales in under a week.",
    shipping: 7.99,
  },
  {
    key: "B06XKH29C8",
    id: 60,
    category: "Web Development",
    name: "The Essential Web Developer Course - Build 12 Websites",
    seller: "Robert Kanaat",
    price: 134.99,
    priceFraction: "00",
    stock: 95,
    star: 4.7,
    starCount: 1150,
    time: 80,
    language: "English",
    img: "https://img-a.udemycdn.com/course/240x135/260756_bac8_3.jpg",
    url: "https://www.udemy.com/course/the-essential-web-developer-course/",
    features:
      "From an absolute beginner, to a certified Web developer, this course will teach you the ABCs of Web development.",
    shipping: 3.99,
  },
];

export default webDev;
